### ISSUE TITLE
What's the result when only using verification loss?

### ISSUE THREAD

**Issue by 1292765944** [layumi/Person-reID-verification#1]
rt

**Comment by layumi** [comment]
You may try it by set the weight of the softmax loss to zero.

**Comment by 1292765944** [comment]
@layumi Could you help me with this error?
`Traceback (most recent call last):
  File "train.py", line 130, in <module>
    data_transforms['train'])
  File "/home/extend/Person-reID-verification-master/tripletfolder.py", line 11, in __init__
    targets = np.asarray([s[1] for s in self.samples])
AttributeError: 'TripletFolder' object has no attribute 'samples'
`

**Comment by layumi** [comment]
Sure. What is the version of your pytorch and torchvision?
It looks like a bug caused by the old torchvision.
You could install the latest torchvision by 
``` 
git clone https://github.com/pytorch/vision
cd vision
python setup.py install
```

**Comment by 1292765944** [comment]
Yes, I just update torchvision to the latest 0.2.1 and it works. Thanks for your help

**Comment by 1292765944** [comment]
@layumi  I firstly reproduce your softmax + verification experiment using the default setting and get slightly worse result.
`Rank@1:0.866686 Rank@5:0.946853 Rank@10:0.966152 mAP:0.701137`
using this command
`python train_new.py --gpu_ids 0 --name ft_ResNet50 --alpha 1.0 --batchsize 32`
So how did you tune the params?

**Comment by Feesics** [comment]
There is no train_new.py in the code, is it a mistake in the command 
python train_new.py --gpu_ids 0 --name ft_ResNet50 --alpha 1.0 --batchsize 32  --data_dir your_data_path

**Comment by layumi** [comment]
@Feesics 
Thanks. It's my mistake.

**Comment by Feesics** [comment]
When I using this command
 **python train.py --gpu_ids 0 --name ft_ResNet50 --alpha 1.0 --batchsize 32**
I got the follwing error:
[Resize(size=(256, 128), interpolation=PIL.Image.BICUBIC), Pad(padding=10, fill=0, padding_mode=constant), RandomCrop(size=(256, 128), padding=None), RandomHorizontalFlip(p=0.5), ToTensor(), Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])]
1.430511474609375e-06
Segmentation fault (core dumped)
Can you tell me how to deal with it?

**Comment by layumi** [comment]
@Feesics 

`Segmentation fault` may be caused by pytorch or some cuda related issue.
Could you try this code https://github.com/layumi/Person_reID_baseline_pytorch first?
It is a classification-based baseline. If it also went wrong, you may need to reinstall pytorch.

**Comment by Feesics** [comment]
Ok, I will try it, thanks.
