### ISSUE TITLE
请问id+verification这个模型，怎样转换成原来的baseline模型啊？

### ISSUE THREAD

**Issue by Deeplearning20** [layumi/Person-reID-verification#9]
您好，请问把loss_verif设成0，是不是就可以转换成之前的baseline模型了啊？https://github.com/layumi/Person_reID_baseline_pytorch

**Comment by layumi** [comment]
@Deeplearning20 
基本相同吧。因为我修改了dataloader的方式，可能会有小不同。

**Comment by Deeplearning20** [comment]
好的，明白了！多谢您！！！
